package pl.kostro.expensesystem.view.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.v7.ui.PasswordField;
import com.vaadin.v7.ui.TextField;
import com.vaadin.v7.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AccountDesign extends VerticalLayout {
  protected Label titleLabel;
  protected TextField usernameField;
  protected Panel emailPanel;
  protected TextField emailField;
  protected TextField emailField2;
  protected Button saveEmailButton;
  protected Panel passwordPanel;
  protected PasswordField oldPasswordField;
  protected PasswordField newPasswordField;
  protected PasswordField newPasswordField2;
  protected Button savePasswordButton;

  public AccountDesign() {
    Design.read(this);
  }
}
