package pl.kostro.expensesystem.view.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBoxGroup;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ChartDesign extends VerticalLayout {
  protected VerticalLayout chartLayout;
  protected VerticalLayout chartLayout2;
  protected CheckBoxGroup<pl.kostro.expensesystem.model.Category> categoryCombo;
  protected CheckBoxGroup<pl.kostro.expensesystem.model.UserLimit> userCombo;
  protected Button searchButton;

  public ChartDesign() {
    Design.read(this);
  }
}
