package pl.kostro.expensesystem.view.design;

import org.vaadin.teemu.VaadinIcons;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

import pl.kostro.expensesystem.Msg;

@SuppressWarnings("serial")
public class DayDesign extends VerticalLayout {

  protected HorizontalLayout navigationLayout;
  protected Button previousDayButton;
  protected PopupDateField thisDateField;
  protected Button nextDayButton;

  protected HorizontalLayout workingLayout;
  protected VerticalLayout showLayout;
  protected GridLayout expensesGrid;
  protected Button backButton;
  protected VerticalLayout categoryLayout;
  
  public DayDesign() {
    setSizeFull();

    // navigationLayout
    navigationLayout = buildNavigationLayout();
    addComponent(navigationLayout);
    setComponentAlignment(navigationLayout, new Alignment(20));

    // workingLayout
    workingLayout = buildWorkingLayout();
    addComponent(workingLayout);
  }

  @AutoGenerated
  private HorizontalLayout buildNavigationLayout() {
    // common part: create layout
    navigationLayout = new HorizontalLayout();
    navigationLayout.setSpacing(true);

    // previousDayButton
    previousDayButton = new Button();
    previousDayButton.setIcon(VaadinIcons.ARROW_LEFT);
    previousDayButton.addStyleName(ValoTheme.BUTTON_ICON_ONLY);
    previousDayButton.addStyleName(ValoTheme.BUTTON_BORDERLESS);
    previousDayButton.setImmediate(true);
    navigationLayout.addComponent(previousDayButton);
    navigationLayout.setComponentAlignment(previousDayButton, new Alignment(33));

    // thisDateField
    thisDateField = new PopupDateField();
    thisDateField.setImmediate(true);
    thisDateField.setDateFormat("dd-MM-yyyy");
    navigationLayout.addComponent(thisDateField);
    navigationLayout.setComponentAlignment(thisDateField, new Alignment(48));

    // nextDayButton
    nextDayButton = new Button();
    nextDayButton.setIcon(VaadinIcons.ARROW_RIGHT);
    nextDayButton.addStyleName(ValoTheme.BUTTON_ICON_ONLY);
    nextDayButton.addStyleName(ValoTheme.BUTTON_BORDERLESS);
    nextDayButton.setImmediate(true);
    navigationLayout.addComponent(nextDayButton);
    navigationLayout.setComponentAlignment(nextDayButton, new Alignment(34));

    return navigationLayout;
  }

  @AutoGenerated
  private HorizontalLayout buildWorkingLayout() {
    // common part: create layout
    workingLayout = new HorizontalLayout();

    // showLayout
    showLayout = buildShowLayout();
    workingLayout.addComponent(showLayout);

    // categoryLayout
    categoryLayout = new VerticalLayout();
    workingLayout.addComponent(categoryLayout);

    return workingLayout;
  }

  @AutoGenerated
  private VerticalLayout buildShowLayout() {
    showLayout = new VerticalLayout();

    // expensesGrid
    expensesGrid = new GridLayout();
    expensesGrid.setMargin(true);
    expensesGrid.setSpacing(true);
    showLayout.addComponent(expensesGrid);

    // backButton
    backButton = new Button();
    backButton.setCaption(Msg.get("day.back"));
    backButton.setImmediate(true);
    showLayout.addComponent(backButton);

    return showLayout;
  }
}
