package pl.kostro.expensesystem.view.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.v7.ui.HorizontalLayout;
import com.vaadin.v7.ui.Label;
import com.vaadin.v7.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainDesign extends HorizontalLayout {
  protected CssLayout menuPart;
  protected HorizontalLayout menuTitle;
  protected Label title;
  protected Button showMenuButton;
  protected CssLayout menuItems;
  protected Label sheetLabel;
  protected VerticalLayout sheetLayout;
  protected Label settingsLabel;
  protected Button addSheetButton;
  protected Button accountButton;
  protected Button logoutButton;
  protected VerticalLayout content;

  public MainDesign() {
    Design.read(this);
  }
}
