package pl.kostro.expensesystem.view.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MonthDesign extends CssLayout {
  protected VerticalLayout root;
  protected Label titleLabel;
  protected Button editButton;
  protected Button chartButton;
  protected VerticalLayout expensePanels;
  protected HorizontalLayout menuLayout;
  protected MenuBar yearMenu;
  protected Button filterButton;
  protected Button findButton;
  protected MenuBar monthMenu;
  protected Panel searchPanel;
  protected ComboBox categoryCombo;
  protected ComboBox userCombo;
  protected TextField formulaField;
  protected ComboBox commentCombo;
  protected Button searchButton;
  protected VerticalLayout mainView;
  protected HorizontalLayout navigationLayout;
  protected Button previousMonthButton;
  protected DateField thisMonthField;
  protected Button nextMonthButton;

  public MonthDesign() {
    Design.read(this);
  }
}
