package pl.kostro.expensesystem.view.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import pl.kostro.expensesystem.components.calendar.ExpenseCalendar;
import pl.kostro.expensesystem.components.table.CategoryTable;
import pl.kostro.expensesystem.components.table.UserLimitTable;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MonthDesign extends HorizontalLayout {
  protected VerticalLayout calendarLayout;
  protected HorizontalLayout navigationLayout;
  protected Button previousMonthButton;
  protected DateField thisMonthField;
  protected Button nextMonthButton;
  protected ExpenseCalendar monthCalendar;
  protected VerticalLayout summaryLayout;
  protected HorizontalLayout dateLayout;
  protected DateField firstDateField;
  protected DateField lastDateField;
  protected CategoryTable categoryTable;
  protected UserLimitTable userLimitTable;

  public MonthDesign() {
    Design.read(this);
  }
}
