package pl.kostro.expensesystem.view.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.v7.ui.HorizontalLayout;
import com.vaadin.v7.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.v7.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import pl.kostro.expensesystem.components.grid.CategoryGrid;
import pl.kostro.expensesystem.components.grid.RealUserLimitGrid;
import pl.kostro.expensesystem.components.grid.UserLimitGrid;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SettingsDesign extends VerticalLayout {
  protected HorizontalLayout headerLayout;
  protected Label titleLabel;
  protected HorizontalLayout toolsLayout;
  protected Button editButton;
  protected Button passwordButton;
  protected Button removeButton;
  protected HorizontalLayout gridLayout;
  protected Panel categoryPanel;
  protected VerticalLayout categoryLayout;
  protected CategoryGrid categoryGrid;
  protected HorizontalLayout categoryButtonLayout;
  protected Button addCategoryButton;
  protected Button moveUpCategoryButton;
  protected Button moveDownCategoryButton;
  protected Button deleteCategoryButton;
  protected Panel realUserPanel;
  protected VerticalLayout realUserLayout;
  protected RealUserLimitGrid realUserGrid;
  protected HorizontalLayout realUserButtonLayout;
  protected Button addRealUserButton;
  protected Button deleteRealUserButton;
  protected Panel userPanel;
  protected VerticalLayout userLayout;
  protected UserLimitGrid userGrid;
  protected HorizontalLayout userButtonLayout;
  protected Button addUserButton;
  protected Button deleteUserButton;

  public SettingsDesign() {
    Design.read(this);
  }
}
