package pl.kostro.expensesystem.view.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserSummaryDesign extends VerticalLayout {
  protected Panel actionPanel;
  protected HorizontalLayout actionsLayout;
  protected ComboBox<pl.kostro.expensesystem.model.UserLimit> userBox;
  protected HorizontalLayout workingLayout;
  protected Grid<pl.kostro.expensesystem.model.UserSummary> userSummaryGrid;

  public UserSummaryDesign() {
    Design.read(this);
  }
}
