package pl.kostro.expensesystem.view;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import pl.kostro.expensesystem.Msg;
import pl.kostro.expensesystem.components.dialog.ConfirmDialog;
import pl.kostro.expensesystem.model.Category;
import pl.kostro.expensesystem.model.Expense;
import pl.kostro.expensesystem.model.ExpenseSheet;
import pl.kostro.expensesystem.service.ExpenseService;
import pl.kostro.expensesystem.service.ExpenseSheetService;
import pl.kostro.expensesystem.utils.DateExpense;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.VaadinSession;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class CategoryExpenseView extends CustomComponent {

  @AutoGenerated
  private VerticalLayout mainLayout;

  @AutoGenerated
  private AddNewExpenseView addNewExpense;

  @AutoGenerated
  private HorizontalLayout expenseLayout;

  @AutoGenerated
  private GridLayout expenseGrid;

  @AutoGenerated
  private Label categoryLabel;
  /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

  private ExpenseSheet expenseSheet;
  private Category category;
  private DayView dayView;

  /**
   * The constructor should first build the main layout, set the composition
   * root and then do any custom initialization.
   * 
   * The constructor will not be automatically regenerated by the visual editor.
   * 
   * @param parentView
   * @param date
   * @param expenseSheet
   * @param category
   * @param dayView
   */
  public CategoryExpenseView(final Calendar calendar, final Category category, DayView dayView) {
    this.expenseSheet = VaadinSession.getCurrent().getAttribute(ExpenseSheet.class);
    this.category = category;
    this.dayView = dayView;
    buildMainLayout();
    setCompositionRoot(mainLayout);

    // TODO add user code here
    categoryLabel.setValue(category.getName());
    addNewExpense.setDayView(dayView);

    prepareExpenseGrid(calendar);
    addNewExpense.buildAddNewExpense(ExpenseService.prepareNewExpense(expenseSheet, calendar.getTime(), category,
        expenseSheet.getUserLimitList().get(0).getUser()), false, calendar);
  }

  private void prepareExpenseGrid(final Calendar calendar) {
    expenseGrid.removeAllComponents();

    List<Expense> expenseList;
    DateExpense dateExpenseMap = ExpenseSheetService.getDateExpenseMap(expenseSheet, calendar.getTime());
    if (dateExpenseMap == null || dateExpenseMap.getCategoryExpenseMap().get(category) == null)
      expenseList = new ArrayList<Expense>();
    else {
      expenseList = dateExpenseMap.getCategoryExpenseMap().get(category).getExpenseList();
    }
    expenseGrid.setColumns(4);
    expenseGrid.setRows(expenseList.size() == 0 ? 1 : expenseList.size());

    for (int i = 0; i < expenseList.size(); i++) {
      Expense expense = expenseList.get(i);
      TextField user = new TextField();
      user.setEnabled(false);
      user.setValue(expense.getUser().getName());
      expenseGrid.addComponent(user, 0, i);

      Button valueButton = new Button(ExpenseService.getValueString(expense));
      valueButton.setImmediate(true);
      valueButton.setWidth("-1px");
      valueButton.setHeight("-1px");
      valueButton.setData(expense);
      expenseGrid.addComponent(valueButton, 1, i);

      valueButton.addClickListener(new Button.ClickListener() {
        @Override
        public void buttonClick(ClickEvent event) {
          if (event.getButton().getData() instanceof Expense) {
            addNewExpense.buildAddNewExpense((Expense) event.getButton().getData(), true, calendar);
          }
        }
      });

      TextField comment = new TextField();
      comment.setEnabled(false);
      comment.setNullRepresentation("");
      comment.setValue(expense.getComment());
      expenseGrid.addComponent(comment, 2, i);

      Button removeButton = new Button();
      removeButton.setCaption("X");
      removeButton.setImmediate(true);
      removeButton.setWidth("-1px");
      removeButton.setHeight("-1px");
      removeButton.setData(expense);
      expenseGrid.addComponent(removeButton, 3, i);

      removeButton.addClickListener(new Button.ClickListener() {
        @Override
        public void buttonClick(ClickEvent event) {
          if (event.getButton().getData() instanceof Expense) {
            final Expense expense = (Expense) event.getButton().getData();
            ConfirmDialog.show(getUI(), Msg.get("category.removeLabel"), Msg.get("category.removeQuestion"),
                Msg.get("category.removeYes"), Msg.get("category.removeNo"), new ConfirmDialog.Listener() {
                  @Override
                  public void onClose(ConfirmDialog dialog) {
                    if (dialog.isConfirmed()) {
                      ExpenseService.removeExpense(expenseSheet, expense);
                      dayView.refreshView(calendar, category);
                    }
                  }
                });
          }
        }
      });
    }
  }

  @AutoGenerated
  private VerticalLayout buildMainLayout() {
    // common part: create layout
    mainLayout = new VerticalLayout();
    mainLayout.setImmediate(false);
    mainLayout.setWidth("100%");
    mainLayout.setHeight("100%");
    mainLayout.setMargin(false);

    // top-level component properties
    setWidth("100.0%");
    setHeight("100.0%");

    // categoryLabel
    categoryLabel = new Label();
    categoryLabel.setImmediate(false);
    categoryLabel.setWidth("-1px");
    categoryLabel.setHeight("-1px");
    categoryLabel.setValue("Label");
    mainLayout.addComponent(categoryLabel);
    mainLayout.setComponentAlignment(categoryLabel, new Alignment(20));

    // expenseLayout
    expenseLayout = buildExpenseLayout();
    mainLayout.addComponent(expenseLayout);
    mainLayout.setComponentAlignment(expenseLayout, new Alignment(48));

    // addNewExpense
    addNewExpense = new AddNewExpenseView();
    addNewExpense.setImmediate(false);
    addNewExpense.setWidth("-1px");
    addNewExpense.setHeight("-1px");
    mainLayout.addComponent(addNewExpense);

    return mainLayout;
  }

  @AutoGenerated
  private HorizontalLayout buildExpenseLayout() {
    // common part: create layout
    expenseLayout = new HorizontalLayout();
    expenseLayout.setImmediate(false);
    expenseLayout.setWidth("-1px");
    expenseLayout.setHeight("-1px");
    expenseLayout.setMargin(false);

    // expenseGrid
    expenseGrid = new GridLayout();
    expenseGrid.setImmediate(false);
    expenseGrid.setWidth("-1px");
    expenseGrid.setHeight("-1px");
    expenseGrid.setMargin(false);
    expenseGrid.setSpacing(true);
    expenseLayout.addComponent(expenseGrid);

    return expenseLayout;
  }

}
