package pl.kostro.expensesystem.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class LoginPage extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public LoginPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new VerticalLayout();
		mainLayout.addComponent(new Label("loginPageLabel"));
		
		HorizontalLayout loginLayout = new HorizontalLayout();
		GridLayout grid = new GridLayout(2, 2);
		grid.addComponent(new Label("loginPage.userNameLabel"));
		grid.addComponent(new TextField());
		grid.addComponent(new Label("loginPage.passwordLabel"));
		grid.addComponent(new PasswordField());
		loginLayout.addComponent(grid);
		Button loginButton = new Button("loginPage.loginButton");
		loginLayout.addComponent(loginButton);
		mainLayout.addComponent(loginLayout);
		
		HorizontalLayout horizontalLayout = new HorizontalLayout();
		Button remindPasswordButton = new Button("loginPage.remindPasswordButton");
		horizontalLayout.addComponent(remindPasswordButton);
		Button registerButton = new Button("loginPage.registerButton");
		horizontalLayout.addComponent(registerButton);
		mainLayout.addComponent(horizontalLayout);
	}

}
