package pl.kostro.expensesystem.components.mainPageComponents;

import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;

import pl.kostro.expensesystem.model.RealUser;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Calendar;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.VerticalLayout;

public class MonthView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Calendar monthCalendar;
	@AutoGenerated
	private MenuBar monthMenu;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MonthView(final RealUser loggedUser, final String year) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		MenuBar.Command monthCommand = new MenuBar.Command() {
			
			@Override
			public void menuSelected(MenuItem selectedItem) {
				// TODO Auto-generated method stub
				try {
					if (selectedItem.getText().equals("styczeñ")) {
						monthCalendar = new Calendar();
						DateFormat df = DateFormat.getDateInstance();
						monthCalendar.setStartDate(df.parse("01-01-"+year));
						monthCalendar.setStartDate(df.parse("10-01-"+year));
					} else if (selectedItem.getText().equals("luty")) {
						monthCalendar = new Calendar();
						DateFormat df = DateFormat.getDateInstance();
						monthCalendar.setStartDate(df.parse("01-02-"+year));
						monthCalendar.setStartDate(df.parse("10-02-"+year));
					}
				}catch(ParseException e) {
					e.printStackTrace();
				}
			}
		};
		
		MenuItem yanuary = monthMenu.addItem("styczeñ", monthCommand);
		MenuItem february = monthMenu.addItem("luty", monthCommand);
		MenuItem march = monthMenu.addItem("marzec", monthCommand);
		MenuItem april = monthMenu.addItem("kwiecieñ", monthCommand);
		MenuItem may = monthMenu.addItem("maj", monthCommand);
		MenuItem june = monthMenu.addItem("czerwiec", monthCommand);
		MenuItem july = monthMenu.addItem("lipiec", monthCommand);
		MenuItem august = monthMenu.addItem("sierpieñ", monthCommand);
		MenuItem september = monthMenu.addItem("wrzesieñ", monthCommand);
		MenuItem october = monthMenu.addItem("paŸdziernik", monthCommand);
		MenuItem november = monthMenu.addItem("listopad", monthCommand);
		MenuItem december = monthMenu.addItem("grudzieñ", monthCommand);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// monthMenu
		monthMenu = new MenuBar();
		monthMenu.setImmediate(false);
		monthMenu.setWidth("100%");
		monthMenu.setHeight("-1px");
		mainLayout.addComponent(monthMenu);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// monthCalendar
		monthCalendar = new Calendar();
		monthCalendar.setImmediate(false);
		monthCalendar.setWidth("-1px");
		monthCalendar.setHeight("-1px");
		mainLayout.addComponent(monthCalendar);
		
		return mainLayout;
	}

}
